name: web_uri
description: >
  A lightweight and compatible Uri class.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/web_uri

environment:
  sdk: ">=1.22.0 <2.0.0-alpha.infinity"

dev_dependencies:
  test: ^0.12.20+8
